# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"            # Location of your package.json
    schedule:
      interval: "daily"       # Check for updates daily
    cooldown:
      default-days: 21

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 21
